#!/bin/bash

# Simplified Docker Development Workflows

echo "🐳 Docker-Based Development Guide"
echo "================================="
echo ""
echo "🔄 Two Main Workflows:"
echo ""
echo "📋 Workflow 1: Container-Attached IDE (Experienced)"
echo "  1. docker-compose up -d continue-vscode-dev"
echo "  2. VS Code → Remote-Containers → Attach to Running Container"
echo "  3. Develop entirely inside container"
echo "  → Complete isolation, consistent environment"
echo ""
echo "📋 Workflow 2: Host Edit + Container Build (New Dev)"
echo "  1. docker-compose up -d continue-vscode-dev"
echo "  2. docker exec continue-vscode-dev bash -c 'cd /app && ./scripts/install-dependencies.sh'"
echo "  3. Edit on host, debug at http://localhost:8080"
echo "  → Familiar tools + consistent builds"
echo ""
echo "🌐 Access Points:"
echo "  • VS Code (browser): http://localhost:8080"
echo "  • GUI development:   http://localhost:5173"
echo "  • Core server:       http://localhost:3000"
echo ""
echo "🏗️  Build Release:"
echo "  ./release.sh  # Creates VSIX package"
echo ""
echo "✨ Key Benefits:"
echo "  • Same environment everywhere"
echo "  • No host dependency conflicts"
echo "  • Choose your preferred workflow"
