#!/bin/bash
echo "🚀 Continue Extension Development Guide"
echo "======================================"
echo ""
echo "📋 Available Commands:"
echo ""
echo "🔧 Development:"
echo "   ./dev-start.sh          - Start development environment"
echo "   ./scripts/dev-start.sh  - (same as above)"
echo ""
echo "🏗️  Building:"
echo "   ./release.sh            - Build VSIX package for release"
echo "   ./scripts/build-release.sh - (same as above)"
echo ""
echo "🧹 Cleanup:"
echo "   ./cleanup.sh            - Stop containers & clean artifacts"
echo "   ./scripts/cleanup.sh    - (same as above)"
echo ""
echo "🔄 Quick Start:"
echo "========================================"
echo "1. ./dev-start.sh       - Setup development"
echo "2. Open http://localhost:8080 in browser"
echo "3. Press F5 to debug extension"
echo "4. ./release.sh         - Build VSIX when ready"
echo ""
echo "✨ Key Benefits:"
echo "   • No host dependencies needed"
echo "   • Consistent Docker environment"
echo "   • One-command workflows"
